# Generated by Django 2.2.4 on 2019-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yogastie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': '客户'},
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=4, verbose_name='用户名'),
        ),
    ]
