# Generated by Django 2.2.4 on 2019-09-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloblog', '0002_auto_20190913_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
